name: Bug Report
description: Create a report to help improve Spegel
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill ot this bug report! Please read the [FAQ](https://spegel.dev/docs/faq/) and check existing issues before submitting a new issue.
  - type: input
    attributes:
      label: Spegel version
      placeholder: eg. v0.0.16
    validations:
      required: true
  - type: input
    attributes:
      label: Kubernetes distribution
      placeholder: eg. AKS, EKS, K3S, Kubeadm...
    validations:
      required: true
  - type: input
    attributes:
      label: Kubernetes version
      placeholder: eg. v1.29.0
    validations:
      required: true
  - type: input
    attributes:
      label: CNI
      placeholder: eg. Calico, Cilium, Azure CNI...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
