name: e2e
on:
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - proxy-mode: iptables
            ip-family: ipv4
          - proxy-mode: iptables
            ip-family: ipv6
          - proxy-mode: ipvs
            ip-family: ipv4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #v5.3.0
        with:
          go-version-file: go.mod
      - name: Run e2e
        run: make test-e2e E2E_PROXY_MODE=${{ matrix.proxy-mode }} E2E_IP_FAMILY=${{ matrix.ip-family }}
